### ISSUE TITLE
Task :react-native-text-input-mask:compileDebugKotlin FAILED

### ISSUE THREAD

**Issue by andreszuluaga-wolox** [react-native-text-input-mask/react-native-text-input-mask#249]
When I`m building, I get this error:

`> Task :react-native-text-input-mask:compileDebugKotlin FAILED
ReactNativeFirebase WARNING: NPM package '@react-native-firebase/dynamic-links' depends on '@react-native-firebase/app' v12.1.0 but found v11.5.0, this might cause build issues or runtime crashes.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.3/userguide/command_line_interface.html#sec:command_line_warnings
281 actionable tasks: 2 executed, 279 up-to-date
e: java.lang.ExceptionInInitializerError
        at org.jetbrains.kotlin.com.intellij.pom.java.LanguageLevel.<clinit>(LanguageLevel.java:25)
        at org.jetbrains.kotlin.com.intellij.core.CoreLanguageLevelProjectExtension.<init>(CoreLanguageLevelProjectExtension.java:26)
        at org.jetbrains.kotlin.com.intellij.core.JavaCoreProjectEnvironment.<init>(JavaCoreProjectEnvironment.java:42)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreProjectEnvironment.<init>(KotlinCoreProjectEnvironment.kt:26)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$ProjectEnvironment.<init>(KotlinCoreEnvironment.kt:121)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$Companion.createForProduction(KotlinCoreEnvironment.kt:425)
        at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.createCoreEnvironment(K2JVMCompiler.kt:226)
        at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:152)
        at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:52)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:88)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:44)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:98)
        at org.jetbrains.kotlin.incremental.IncrementalJvmCompilerRunner.runCompiler(IncrementalJvmCompilerRunner.kt:386)
        at org.jetbrains.kotlin.incremental.IncrementalJvmCompilerRunner.runCompiler(IncrementalJvmCompilerRunner.kt:110)
        at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileIncrementally(IncrementalCompilerRunner.kt:286)
        at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileImpl$rebuild(IncrementalCompilerRunner.kt:99)
        at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileImpl(IncrementalCompilerRunner.kt:114)
        at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compile(IncrementalCompilerRunner.kt:74)
        at org.jetbrains.kotlin.daemon.CompileServiceImplBase.execIncrementalCompiler(CompileServiceImpl.kt:607)
        at org.jetbrains.kotlin.daemon.CompileServiceImplBase.access$execIncrementalCompiler(CompileServiceImpl.kt:96)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1659)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:357)
        at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
        at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:691)
        at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:587)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:828)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:705)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:704)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected void java.util.ResourceBundle.setParent(java.util.ResourceBundle) accessible: module java.base does not "opens java.util" to unnamed module @13545af8
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
        at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
        at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
        at org.jetbrains.kotlin.com.intellij.util.ReflectionUtil.makeAccessible(ReflectionUtil.java:252)
        at org.jetbrains.kotlin.com.intellij.util.ReflectionUtil.getDeclaredMethod(ReflectionUtil.java:269)
        at org.jetbrains.kotlin.com.intellij.DynamicBundle.<clinit>(DynamicBundle.java:22)
        ... 38 more

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-text-input-mask:compileDebugKotlin'.
> Internal compiler error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 26s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup. Run CLI with --verbose flag for more details.
Error: Command failed: ./gradlew app:installDevDebug -PreactNativeDevServerPort=8081
e: java.lang.ExceptionInInitializerError
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

I have:

![Screen Shot 2021-08-02 at 2 24 02 PM](https://user-images.githubusercontent.com/75996952/127912797-50d7ed45-d48c-49eb-9be4-2cd4d93691d5.png)

![Screen Shot 2021-08-02 at 2 25 12 PM](https://user-images.githubusercontent.com/75996952/127913029-d6ea8077-1919-4baa-92fe-365d1110a3d9.png)

![Screen Shot 2021-08-02 at 2 25 19 PM](https://user-images.githubusercontent.com/75996952/127913022-50482e60-66b6-4528-b472-2bfd32345ef4.png)

![Screen Shot 2021-08-02 at 2 25 45 PM](https://user-images.githubusercontent.com/75996952/127913028-1225316c-d3e8-446d-8e19-711da3ffe5b0.png)

**Comment by cloudworkpro-hassen** [comment]
How did you fix this?

**Comment by VasylenckoSlava** [comment]
Go to  **android/gradle.properties**  and **paste org.gradle.jvmargs=-Dkotlin.daemon.jvm.options=--illegal-access=permit**

**Comment by crzycoder** [comment]
any solution?

**Comment by KianooshSoleimani** [comment]
> any solution?

I have just updated kotlin version of react-native-text-input-mask build.gradle to 1.6.10 and errors gone

**Comment by KianooshSoleimani** [comment]
I think this is a good solution 
```
https://github.com/react-native-text-input-mask/react-native-text-input-mask/issues/271#issue-1304374538
```

**Comment by crzycoder** [comment]
@KianooshSoleimani do you know any other library which support decimal character as input upto 2 decimal

**Comment by KianooshSoleimani** [comment]
> @KianooshSoleimani do you know any other library which support decimal character as input upto 2 decimal

maybe you could try to write something in js with regex

**Comment by crzycoder** [comment]
`let regex = /^[+-]?([1-9]+\.?[0-9]*|\.[0-9]+)$/;`
thats the regex I'm using but it's fail when user type like 1200.

**Comment by KianooshSoleimani** [comment]
> `let regex = /^[+-]?([1-9]+\.?[0-9]*|\.[0-9]+)$/;` thats the regex I'm using but it's fail when user type like 1200.

try this
```
x?.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ',')
```

**Comment by crzycoder** [comment]
`x?.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ',')`
check the output of 1200.54.84. it's allow me to input 2 dots.

**Comment by KianooshSoleimani** [comment]
> `x?.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ',')` check the output of 1200.54.84. it's allow me to input 2 dots.

you wanna format something to date?

**Comment by crzycoder** [comment]
I want validate string that is correct decimal upto two points.
'123.45'  ==>> that's a valid case.
'123..45'  ==>> that's not a valid case.
'123.454'  ==>> that's not a valid case.
'123.45.4'  ==>> that's not a valid case.

**Comment by KianooshSoleimani** [comment]
> I want validate string that is correct decimal upto two points. '123.45' ==>> that's a valid case. '123..45' ==>> that's not a valid case. '123.454' ==>> that's not a valid case. '123.45.4' ==>> that's not a valid case.

what is your idea about this
```
unction validate(txt) {

  const splitted = txt.split('.');

  if (splitted.length > 2) {
     throw new Error('txt not valid')
  }

  if (splitted[1].length > 2) {
    throw new Error('txt not valid')
  }

  return txt;

}
```

**Comment by crzycoder** [comment]
` text.indexOf('.') >= 0
                              ? text.substr(0, text.indexOf('.')) +
                                text.substr(text.indexOf('.'), 3)
                              : text;`
                              
done the trick

**Comment by relez** [comment]
Hey guys, have you fixed the issue when android build fails? This is what I am getting:
```
[RUN_GRADLEW] FAILURE: Build failed with an exception.
[RUN_GRADLEW] * What went wrong:
[RUN_GRADLEW] Execution failed for task ':react-native-text-input-mask:compileReleaseKotlin'.
[RUN_GRADLEW] > Compilation error. See log for more details
[RUN_GRADLEW] * Try:
[RUN_GRADLEW] > Run with --stacktrace option to get the stack trace.
[RUN_GRADLEW] > Run with --info or --debug option to get more log output.
[RUN_GRADLEW] > Run with --scan to get full insights.
[RUN_GRADLEW] * Get more help at https://help.gradle.org
[RUN_GRADLEW] BUILD FAILED in 1m 10s
[RUN_GRADLEW] Error: Gradle build failed with unknown error. Please see logs for the "Run gradlew" phase.

Build failed
Gradle build failed with unknown error. Please see logs for the "Run gradlew" phase.
    Error: npx exited with non-zero code: 1
```
Thanks!

**Comment by fatihyildizhan** [comment]
I have this problem with RN 0.63

**Comment by johhansantana** [comment]
issue was hijacked lol. Any solution to the original problem? The latest version seems to have all the patches suggested here but still have the error:

```
'compileDebugJavaWithJavac' task (current target is 11) and 'compileDebugKotlin' task (current target is 1.8) jvm target compatibility should be set to the same Java version.
```

**Comment by augustosnk12** [comment]
@johhansantana your tip worked for me. Thanks ❤
